import os
import sys
import json
import sqlite3
from collections import defaultdict

def analyze():
    db_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'instance', 'iot_security.db')
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # Find the latest run_id from predictions
    cursor.execute("SELECT run_id FROM predictions ORDER BY timestamp DESC LIMIT 1")
    row = cursor.fetchone()
    if not row:
        print("No predictions found.")
        return
    latest_run_id = row['run_id']
    
    # We want ONLY the 9 alerts generated by the latest live monitoring run.
    # The user says there were exactly 9. Let's fetch them based on run_id and threat=1
    cursor.execute('''
        SELECT a.id as alert_id, p.* 
        FROM alerts a 
        JOIN predictions p ON a.prediction_id = p.id 
        WHERE p.run_id = ? AND p.threat = 1
        ORDER BY p.timestamp ASC
    ''', (latest_run_id,))
    
    alerts = cursor.fetchall()
    print(f"Found {len(alerts)} alerts in the latest run ({latest_run_id}).")

    if len(alerts) == 0:
        # Fallback to getting the last 9 alerts overall if run_id is somehow missing or different
        cursor.execute('''
            SELECT a.id as alert_id, p.* 
            FROM alerts a 
            JOIN predictions p ON a.prediction_id = p.id 
            ORDER BY p.timestamp DESC LIMIT 9
        ''')
        alerts = cursor.fetchall()[::-1]
        print(f"Fallback: grabbed last {len(alerts)} alerts.")

    by_src_ip = defaultdict(list)

    print("\n--- A. 9-ALERT FORENSIC TABLE ---")
    for i, a in enumerate(alerts, 1):
        explanation = json.loads(a['explanation']) if a['explanation'] else {}
        top_features = explanation.get('top_features', [])
        src_port = explanation.get('src_port', 'N/A')
        dst_port = explanation.get('dst_port', 'N/A')
        protocol_raw = explanation.get('protocol_raw', {})
        
        # protocol detection
        proto_str = "Unknown"
        if protocol_raw.get('proto_tcp') == 1: proto_str = "TCP"
        elif protocol_raw.get('proto_udp') == 1: proto_str = "UDP"
        elif protocol_raw.get('proto_icmp') == 1: proto_str = "ICMP"
        elif protocol_raw.get('proto_other') == 1: proto_str = "Other"

        print(f"\nAlert #{i}")
        print(f"Timestamp: {a['timestamp']}")
        print(f"Alert ID: {a['alert_id']}")
        print(f"Prediction ID: {a['id']}")
        print(f"Source IP: {a['source_ip']}")
        print(f"Destination IP: {a['dest_ip']}")
        print(f"Source Port: {src_port}")
        print(f"Destination Port: {dst_port}")
        print(f"Protocol: {proto_str}")
        print(f"Confidence: {a['confidence']}")
        
        print("Top 5 SHAP features:")
        # Parse features from top_features to get flow stats
        fwd_pkts = fwd_bytes = bwd_pkts = bwd_bytes = flow_dur = "N/A"
        for tf in top_features:
            print(f"  - {tf['feature']}: raw={tf['raw_value']}, impact={tf['impact']:.4f}")
            if tf['feature'] == 'Total Fwd Packets': fwd_pkts = tf['raw_value']
            if tf['feature'] == 'Total Length of Fwd Packets': fwd_bytes = tf['raw_value']
            if tf['feature'] == 'Total Backward Packets': bwd_pkts = tf['raw_value']
            if tf['feature'] == 'Total Length of Bwd Packets': bwd_bytes = tf['raw_value']
            if tf['feature'] == 'Flow Duration': flow_dur = tf['raw_value']
        
        print("Relevant Flow Statistics (from available SHAP data, if present):")
        print(f"  Fwd Pkts: {fwd_pkts}, Bwd Pkts: {bwd_pkts}")
        print(f"  Fwd Bytes: {fwd_bytes}, Bwd Bytes: {bwd_bytes}")
        print(f"  Flow Duration: {flow_dur}")

        # Grouping
        by_src_ip[a['source_ip']].append({
            'ts': a['timestamp'],
            'src_port': src_port,
            'dst_port': dst_port,
            'proto': proto_str,
            'conf': a['confidence']
        })

    print("\n--- B. GROUPED BY SOURCE IP ---")
    for src, group in by_src_ip.items():
        print(f"\nSource {src}:")
        print(f"- Number of alerts: {len(group)}")
        ports_set = set((g['src_port'], g['dst_port']) for g in group)
        print(f"- Ports (src -> dst): {ports_set}")
        protos = set(g['proto'] for g in group)
        print(f"- Protocols: {protos}")
        timestamps = [g['ts'] for g in group]
        print(f"- Timestamps: {timestamps}")

if __name__ == '__main__':
    analyze()
